"""empty message

Revision ID: ae0c7479fb9b
Revises: 58c329f91f4f
Create Date: 2020-03-31 16:52:32.313344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0c7479fb9b'
down_revision = '58c329f91f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('Avatar', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'Avatar')
    # ### end Alembic commands ###
